// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Sat Nov 26 10:52:16 2022

IU IU_inst
(
	.CLOCK(CLOCK_sig) ,	// input  CLOCK_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.ROW(ROW_sig) ,	// input [3:0] ROW_sig
	.TRIG(TRIG_sig) ,	// output  TRIG_sig
	.COL(COL_sig) ,	// output [3:0] COL_sig
	.VALUE(VALUE_sig) ,	// output [3:0] VALUE_sig
	.OUT(OUT_sig) ,	// output [15:0] OUT_sig
	.BSM(BSM_sig) ,	// output [7:0] BSM_sig
	.TWOSCOMP(TWOSCOMP_sig) ,	// output [7:0] TWOSCOMP_sig
	.VALID(VALID_sig) 	// output  VALID_sig
);

